// Dev-only build step -- see package.json's description and
// sidebar.template.html's header comment for why this exists at all.
// Not loaded by the extension; run manually (`npm install && node build.js`)
// whenever sidebar.template.html changes.
const fs = require("fs");
const path = require("path");
const { compile } = require("@vue/compiler-dom");

const templatePath = path.join(__dirname, "..", "sidebar.template.html");
const outPath = path.join(__dirname, "..", "sidebar.render.generated.js");

const template = fs.readFileSync(templatePath, "utf8");

const compileErrors = [];
const { code } = compile(template, {
  mode: "function",
  hoistStatic: true,
  prefixIdentifiers: false,
  comments: false, // drop sidebar.template.html's header comment instead of baking it into a runtime _createCommentVNode
  onError: (err) => compileErrors.push(err),
});

if (compileErrors.length) {
  for (const err of compileErrors) console.error(err);
  process.exit(1);
}

const indented = code
  .split("\n")
  .map((line) => (line ? "  " + line : line))
  .join("\n");

const out = `// AUTO-GENERATED by webext/scripts/build.js from webext/sidebar.template.html.
// Do not hand-edit: edit that file and regenerate this one (see its header
// comment for the exact command). Loaded as a content script, ahead of
// sidebar.js (see manifest.json), which reads window.__bdSidebarRender.
window.__bdSidebarRender = (function () {
${indented}
})();
`;

fs.writeFileSync(outPath, out);
console.log(`Wrote ${path.relative(process.cwd(), outPath)}`);
