"""add has_normal_variant to skins

Revision ID: 4e1d74745f47
Revises: f4c266971928
Create Date: 2026-07-31 13:45:18.162033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1d74745f47'
down_revision: Union[str, Sequence[str], None] = 'f4c266971928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins', sa.Column('has_normal_variant', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skins', 'has_normal_variant')
    # ### end Alembic commands ###
