"""create skins and contracts

Revision ID: 94018f0ef23c
Revises: 
Create Date: 2026-08-05 13:41:15.985371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94018f0ef23c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rarity_name', sa.String(), nullable=False),
    sa.Column('target_rarity_name', sa.String(), nullable=False),
    sa.Column('stattrak', sa.Boolean(), nullable=False),
    sa.Column('input_cost', sa.Float(), nullable=False),
    sa.Column('expected_output_value', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('cvar_5pct', sa.Float(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_simulated_at', sa.DateTime(), nullable=False),
    sa.Column('input_lines', sa.JSON(), nullable=False),
    sa.Column('outcomes', sa.JSON(), nullable=False),
    sa.Column('missing_input_price_names', sa.JSON(), nullable=False),
    sa.Column('missing_output_price_names', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weapon_name', sa.String(), nullable=True),
    sa.Column('pattern_name', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('rarity_name', sa.String(), nullable=True),
    sa.Column('rarity_color', sa.String(), nullable=True),
    sa.Column('min_float', sa.Float(), nullable=True),
    sa.Column('max_float', sa.Float(), nullable=True),
    sa.Column('stattrak', sa.Boolean(), nullable=False),
    sa.Column('souvenir', sa.Boolean(), nullable=False),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('paint_index', sa.String(), nullable=True),
    sa.Column('collection_id', sa.String(), nullable=True),
    sa.Column('collection_name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('last_price_recalculated_at', sa.DateTime(), nullable=True),
    sa.Column('last_price_calculation_data_point_recency', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skins')
    op.drop_table('contracts')
    # ### end Alembic commands ###
