"""add market items and price observations

Revision ID: 998b4039fc43
Revises: 4e1d74745f47
Create Date: 2026-07-31 14:08:02.446118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998b4039fc43'
down_revision: Union[str, Sequence[str], None] = '4e1d74745f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('skin_id', sa.String(), nullable=False),
    sa.Column('market_hash_name', sa.String(), nullable=False),
    sa.Column('wear_name', sa.String(), nullable=True),
    sa.Column('stattrak', sa.Boolean(), nullable=False),
    sa.Column('souvenir', sa.Boolean(), nullable=False),
    sa.Column('phase', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_hash_name', 'phase')
    )
    op.create_table('market_item_external_ids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_item_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['market_item_id'], ['market_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_item_id', 'source')
    )
    op.create_table('price_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_item_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['market_item_id'], ['market_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_observations')
    op.drop_table('market_item_external_ids')
    op.drop_table('market_items')
    # ### end Alembic commands ###
