"""add hourly listing prices and market aggregates

Revision ID: e7f9d21d77d2
Revises: 998b4039fc43
Create Date: 2026-08-02 10:14:49.551856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f9d21d77d2'
down_revision: Union[str, Sequence[str], None] = '998b4039fc43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hourly_listing_prices',
    sa.Column('market_item_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('bucket', sa.DateTime(), nullable=False),
    sa.Column('open_ask', sa.Float(), nullable=True),
    sa.Column('high_ask', sa.Float(), nullable=True),
    sa.Column('low_ask', sa.Float(), nullable=True),
    sa.Column('close_ask', sa.Float(), nullable=True),
    sa.Column('ask_volume', sa.Integer(), nullable=True),
    sa.Column('open_bid', sa.Float(), nullable=True),
    sa.Column('high_bid', sa.Float(), nullable=True),
    sa.Column('low_bid', sa.Float(), nullable=True),
    sa.Column('close_bid', sa.Float(), nullable=True),
    sa.Column('bid_volume', sa.Integer(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['market_item_id'], ['market_items.id'], ),
    sa.PrimaryKeyConstraint('market_item_id', 'source', 'bucket')
    )
    op.create_table('hourly_market_aggregates',
    sa.Column('market_item_id', sa.String(), nullable=False),
    sa.Column('bucket', sa.DateTime(), nullable=False),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('ask_volume', sa.Integer(), nullable=True),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('bid_volume', sa.Integer(), nullable=True),
    sa.Column('hourly_volume', sa.Float(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['market_item_id'], ['market_items.id'], ),
    sa.PrimaryKeyConstraint('market_item_id', 'bucket')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hourly_market_aggregates')
    op.drop_table('hourly_listing_prices')
    # ### end Alembic commands ###
