"""create collections and skins tables

Revision ID: f4c266971928
Revises: 
Create Date: 2026-07-31 12:52:06.156087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c266971928'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('weapon_name', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('pattern_name', sa.String(), nullable=True),
    sa.Column('rarity_name', sa.String(), nullable=True),
    sa.Column('rarity_color', sa.String(), nullable=True),
    sa.Column('min_float', sa.Float(), nullable=True),
    sa.Column('max_float', sa.Float(), nullable=True),
    sa.Column('stattrak', sa.Boolean(), nullable=False),
    sa.Column('souvenir', sa.Boolean(), nullable=False),
    sa.Column('paint_index', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('collection_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skins')
    op.drop_table('collections')
    # ### end Alembic commands ###
